package com.demo.entities;
// Generated Aug 29, 2023, 5:41:03 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Benhnhan generated by hbm2java
 */
@Entity
@Table(name = "benhnhan")
public class Benhnhan implements java.io.Serializable {

	private Integer mabn;
	private String tenbn;
	private Date ngaysinh;
	private String gioitinh;
	private String username;
	private String password;
	private Set<Lichkham> lichkhams = new HashSet<Lichkham>(0);

	public Benhnhan() {
	}

	public Benhnhan(String tenbn, Date ngaysinh, String gioitinh, String username, String password) {
		this.tenbn = tenbn;
		this.ngaysinh = ngaysinh;
		this.gioitinh = gioitinh;
		this.username = username;
		this.password = password;
	}

	public Benhnhan(String tenbn, Date ngaysinh, String gioitinh, String username, String password,
			Set<Lichkham> lichkhams) {
		this.tenbn = tenbn;
		this.ngaysinh = ngaysinh;
		this.gioitinh = gioitinh;
		this.username = username;
		this.password = password;
		this.lichkhams = lichkhams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mabn", unique = true, nullable = false)
	public Integer getMabn() {
		return this.mabn;
	}

	public void setMabn(Integer mabn) {
		this.mabn = mabn;
	}

	@Column(name = "tenbn", nullable = false, length = 250)
	public String getTenbn() {
		return this.tenbn;
	}

	public void setTenbn(String tenbn) {
		this.tenbn = tenbn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", nullable = false, length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "gioitinh", nullable = false, length = 50)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "username", nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benhnhan")
	public Set<Lichkham> getLichkhams() {
		return this.lichkhams;
	}

	public void setLichkhams(Set<Lichkham> lichkhams) {
		this.lichkhams = lichkhams;
	}

}
